#!/usr/bin/env zsh
# vim:autoindent:expandtab:ts=4

dotfiles=(.aliases.csh .screenrc .tcshrc .vimrc .bcrc .zshenv .zshrc .zprofile)
pushd `dirname $0` > /dev/null
linkdir=`pwd -L`
popd > /dev/null

for file in $dotfiles; do
    if [[ ! -f ~/$file ]]; then
        ln -s $linkdir/$file ~/$file
    fi
done

if [[ ! -d ~/.vim/syntax ]]; then
    mkdir -p ~/.vim/syntax
fi
if [[ ! -f ~/.vim/syntax/proto.vim ]]; then
    ln -s $linkdir/proto.vim ~/.vim/syntax/proto.vim
fi

if [[ ! -d ~/.config/powerline/themes/shell/ ]]; then
    mkdir -p ~/.config/powerline/themes/shell/ 
fi
if [[ ! -f ~/.config/powerline/themes/shell/default.json ]]; then
    ln -s $linkdir/default.json ~/.config/powerline/themes/shell/default.json
fi

ipython=`which ipython`
if [[ -n $ipython && ! -d ~/.ipython ]]; then
    ipython profile create
fi
if [[ -n $ipython ]]; then 
    if [[ -f ~/.ipython/profile_default/ipython_config.py ]]; then
        rm ~/.ipython/profile_default/ipython_config.py 
    fi
    if [[ ! -h ~/.ipython/profile_default/ipython_config.py ]]; then
        ln -fs $linkdir/ipython_config.py ~/.ipython/profile_default/ipython_config.py
    fi
fi

