#!/usr/bin/env bash
# vim:autoindent:expandtab:ts=4

dotfiles='.aliases.csh .screenrc .tcshrc .vimrc .bcrc .zshenv .zshrc'
pushd `dirname $0` > /dev/null
linkdir=`pwd -L`
popd > /dev/null

for file in $dotfiles; do
    if [[ ! -f ~/$file ]]; then
        ln -s $linkdir/$file ~/$file
    fi
done

if [[ ! -d ~/.vim/syntax ]]; then
    mkdir -p ~/.vim/syntax
fi
if [[ ! -f ~/.vim/syntax/proto.vim ]]; then
    ln -s $linkdir/proto.vim ~/.vim/syntax/proto.vim
fi
